export const TASK_PROPS_TO_REMOVE = [
    "userId",
    "sectionId",
    "parentId",
    "addedByUid",
    "assignedByUid",
    "responsibleUid",
    "deadline",
    "checked",
    "description",
    "isDeleted",
    "addedAt",
    "completedAt",
    "updatedAt",
    "noteCount",
    "isCollapsed",
    "dayOrder",
    "projectId",
];

export const TASK_RENAME_MAP = {
    projectId: "contextId",
};

export const CONTEXT_PROPS_TO_REMOVE = [
    "canAssignTasks",
    "createdAt",
    "isArchived",
    "isDeleted",
    "isFavorite",
    "isFrozen",
    "updatedAt",
    "viewStyle",
    "defaultOrder",
    "description",
    "isCollapsed",
    "isShared",
    "parentId",
];

export const USER_PROPS_TO_REMOVE = [
    "activated_user",
    "auto_reminder",
    "avatar_big",
    "avatar_medium",
    "avatar_s640",
    "avatar_small",
    "business_account_id",
    "completed_count",
    "date_format",
    "deleted_at",
    "feature_identifier",
    "features",
    "has_magic_number",
    "has_password",
    "has_started_a_trial",
    "image_id",
    "id",
    "inbox_project_id",
    "is_celebrations_enabled",
    "is_deleted",
    "is_premium",
    "joinable_workspace",
    "joined_at",
    "karma",
    "karma_trend",
    "lang",
    "mfa_enabled",
    "onboarding_level",
    "onboarding_persona",
    "onboarding_role",
    "onboarding_started",
    "onboarding_team_mode",
    "onboarding_use_cases",
    "premium_status",
    "premium_until",
    "shard_id",
    "share_limit",
    "sort_order",
    "start_day",
    "start_page",
    "theme_id",
    "time_format",
    "unique_prefix",
    "verification_status",
    "websocket_url",
    "weekend_start_day",
];
